[package]
name = "jsfuck-compiler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
swc_core = { version = "56.0.0", features = ["common", "ecma_parser", "ecma_ast", "ecma_codegen", "ecma_visit"] }
wasm-bindgen = "0.2.108"
